### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by darkpandarts** [giomatfois62/rofi-desktop#1]
All these look super useful, but it would be really good if you could possibly add some documentation to the scripts themselves to indicate how they work as not everyone is a proficient coder. It is difficult to understand what some of them do :)

a good example:
https://github.com/gotbletu/shownotes/blob/master/rofi-scripts-collection/rofi-surfraw-bookmarks.sh

Really like the work you've done here!

**Comment by giomatfois62** [comment]
Glad you find these useful :)
I plan to fully comment all the scripts when i have some more time on my hands.

**Comment by darkpandarts** [comment]
awesome! many thanks! :)

**Comment by giomatfois62** [comment]
I added descriptions and dependencies on most of the scripts (at least the ones made or heavily modified by me) and implemented a configuration system, where you can override some of the scripts' variables by sourcing the "config" file. 
Hopefully this work will solve your issue.

**Comment by darkpandarts** [comment]
Thanks very much! :o)
