### ISSUE TITLE
typo: README.md

### ISSUE THREAD

**Issue by rharmonson** [giomatfois62/rofi-desktop#2]
You have a typo in the README.md.

Currently it reads:

`./scripts/rofi-desktop.sh -s # shows file search menu`

and it should read:

`./scripts/rofi-desktop.sh -f # shows file search menu`

Minor issue but I know that I would prefer someone point it out. I make typos all the time. :)

Just cloned your repo and exploring it. I use rofi and was looking for something new. Your project looks promising.

**Comment by giomatfois62** [comment]
Hey thanks for the correction, I've updated the project readme. 
Have fun with the scripts! Let me know if there's something you wold like added or improved in the collection.
