### ISSUE TITLE
cannot make custom menus work

### ISSUE THREAD

**Issue by jmlucjav** [giomatfois62/rofi-desktop#3]
hi,

I am trying to use custom menus, but I must be missing something. I am doing the simplest thing I can think of:

- download/unzip the project, don't modify anything yet
- run drun.sh
- how do I get the sample entries in rofi-desktop/scripts/menus/Custom Menu.json to show up? I try 'neof' in drun/run and cannot find it, I expected this entry to kick in...

```
  {
    "name": "neofetch",
    "command": "xterm -e bash -c 'neofetch;read'"
  },   
```              

any idea what am I missing?

thanks!

**Comment by giomatfois62** [comment]
drun.sh shows a merged menu with also other system applications, but it currently does not support the custom menus. To show them you need to run the script rofi-desktop.sh in the "scripts" folder.  
Using drun.sh though it's very easy to add your custom entries, just create a .desktop file in the "applications" folder and set the Name and Exec keys (look at one of the files as example). You can even set a custom icon for your entry that will show up in profile.

**Comment by jmlucjav** [comment]
understood, thanks!
